Repository openwebwork/webwork2, pull requests merged in 2021-05, with the labels that each got.

#1358 Use student id for password
  lib/WeBWorK/ContentGenerator/Instructor/AddUsers.pm
Labels: essentially ready to merge, priority 1 (high)

#1352 Make sure that translations are not saved to simple.conf when editing the course configuration
  conf/defaults.config
  lib/WeBWorK/ContentGenerator/Instructor/Config.pm
Labels: Multilingual, essentially ready to merge, priority2 (moderate)

#1329 Update the other formats with the features added to the simple_format in #1301
  htdocs/js/apps/LocalStorage/localstorage.js
  htdocs/js/apps/ProblemSetDetail2/problemsetdetail2.js
  htdocs/js/apps/SetMaker/setmaker.js
  lib/FormatRenderedProblem.pm
  lib/WebworkClient/debug_format.pl
  lib/WebworkClient/json_format.pl
  lib/WebworkClient/simple2_format.pl
  lib/WebworkClient/simple_format.pl
  lib/WebworkClient/standard_format.pl
  lib/WebworkClient/sticky_format.pl
  lib/WebworkWebservice/RenderProblem.pm
Labels: priority 1 (high)

#1372 Minor template and theme fixes
  htdocs/themes/math4-green/math4-coloring.css
  htdocs/themes/math4-red/math4-coloring.css
  htdocs/themes/math4/gateway.template
  htdocs/themes/math4/math4-overrides.css.dist
Labels: essentially ready to merge, priority3 (low)

#1376 switch SQL::Abstract to SQL::Abstract::Classic
  bin/check_modules.pl
  lib/WeBWorK/DB/Schema/NewSQL/Merge.pm
  lib/WeBWorK/DB/Schema/NewSQL/Std.pm
  lib/WeBWorK/DB/Utils/SQLAbstractIdentTrans.pm
Labels: priority 1 (high)

#1374 Adjust ADD_JS_FILE handling code to deal with new third parameter
  lib/FormatRenderedProblem.pm
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
Labels: NeedsTesting, priority2 (moderate)
