Repository openwebwork/webwork2, pull requests merged in 2021-08, with the labels that each got.

#1456 Bugfix: JITAR problem sets 'save' not respecting nested problems
  htdocs/js/apps/ProblemSetDetail/problemsetdetail.js
Labels: priority 1 (high)

#1478 Error with utf8 characters when exporting classlist.
  lib/WeBWorK/File/Classlist.pm
Labels: Multilingual, essentially ready to merge, priority2 (moderate)

#1479 Fix for issue 1477 - uses a revised method of getting "tab titles" in Classlist editor / Homework set editor /Achievement editor into the translation files
  lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
  lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm
  lib/WeBWorK/ContentGenerator/Instructor/UserList.pm
  lib/WeBWorK/Localize/cs_CZ.po
  lib/WeBWorK/Localize/en.po
  lib/WeBWorK/Localize/en_us.po
  lib/WeBWorK/Localize/es.po
  lib/WeBWorK/Localize/fr.po
  lib/WeBWorK/Localize/heb.po
  lib/WeBWorK/Localize/hu.po
  lib/WeBWorK/Localize/ko.po
  lib/WeBWorK/Localize/ru_RU.po
  lib/WeBWorK/Localize/tr.po
  lib/WeBWorK/Localize/webwork2.pot
  lib/WeBWorK/Localize/zh_CN.po
  lib/WeBWorK/Localize/zh_hk.po
Labels: Multilingual, priority3 (low)
