Repository openwebwork/webwork2, pull requests merged in 2021-06, with the labels that each got.

#1309 Add a script that will upgrade the types of columns in the database.
  bin/upgrade-database-to-utf8mb4.pl
Labels: priority2 (moderate)

#1331 Pass information on the course timezone to the achievements
  courses.dist/modelCourse/templates/achievements/crack_o_dawn.at
  courses.dist/modelCourse/templates/achievements/night_owl.at
  lib/WeBWorK/AchievementEvaluator.pm
Labels: Put comment in release notes

#1206 Allow UTF-8 in achievement export/import/score
  lib/WeBWorK/ContentGenerator/Instructor/AchievementList.pm
Labels: Multilingual, priority3 (low)

#1402 Change LTIAdvanced.pm so that all new logins get logged + some other fixes - version 2
  conf/authen_LTI.conf.dist
  lib/WeBWorK/Authen/LTIAdvanced.pm
Labels: NeedsTesting, priority 1 (high)
