Repository openwebwork/webwork2, pull requests merged in 2021-04, with the labels that each got.

#1307 SameSite cookie default to Lax
  conf/defaults.config
  conf/localOverrides.conf.dist
Labels: priority2 (moderate)

#1288 Add an option to disable MathQuill answer boxes per response
  htdocs/js/apps/MathQuill/mqeditor.css
  htdocs/js/apps/MathQuill/mqeditor.js
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
  lib/WeBWorK/ContentGenerator/ProblemUtil/ProblemUtil.pm
Labels: Put comment in release notes

#1294 Change the MathJax config to use its default color setup instead of colorv2
  htdocs/js/apps/MathJaxConfig/mathjax-config.js
  htdocs/themes/math4/gateway.template
  htdocs/themes/math4/simple.template
  htdocs/themes/math4/system.template
Labels: Put comment in release notes, priority2 (moderate)

#1306 Fix POD generation errors.
  bin/dev_scripts/PODParser.pm
  bin/dev_scripts/PODtoHTML.pm
  bin/dev_scripts/generate-ww-pg-pod.pl
  bin/remove_stale_images
  bin/updateOPLextras.pl
  bin/ww_purge_old_nonces
  lib/WeBWorK/ContentGenerator.pm
  lib/WeBWorK/ContentGenerator/instructorXMLHandler.pm
  lib/WeBWorK/ContentGenerator/renderViaXMLRPC.pm
  lib/WeBWorK/FakeRequest.pm
  lib/WeBWorK/NPL.pm
  lib/WeBWorK/Utils/CourseIntegrityCheck.pm
  lib/WeBWorK/Utils/CourseManagement.pm
  lib/WeBWorK/Utils/ListingDB.pm
  lib/WebworkClient.pm
  lib/WebworkSOAP.pm
  lib/WebworkSOAP/Classes/GlobalProblem.pm
  lib/WebworkSOAP/Classes/GlobalSet.pm
  lib/WebworkSOAP/Classes/Key.pm
  lib/WebworkSOAP/Classes/Password.pm
  lib/WebworkSOAP/Classes/Permission.pm
  lib/WebworkSOAP/Classes/User.pm
  lib/WebworkSOAP/Classes/UserProblem.pm
  lib/WebworkSOAP/Classes/UserSet.pm
  lib/WebworkWebservice.pm
  lib/WebworkWebservice/SetActions.pm
Labels: priority2 (moderate)

#1320 Add an option for setting the application (dvisvgm or pdf2svg) used by the PGtikz.pl macro to generate svg images
  Dockerfile
  bin/check_modules.pl
  conf/defaults.config
  conf/localOverrides.conf.dist
  conf/site.conf.dist
Labels: Put comment in release notes, priority2 (moderate)
