Repository openwebwork/webwork2, pull requests merged in 2021-03, with the labels that each got.

#1190 Revised "WeBWorK errors" page code + error.log records
  Dockerfile
  bin/check_modules.pl
  conf/webwork.apache2.4-config.dist
  docker-compose.yml
  lib/Apache/WeBWorK.pm
Labels: Enhancement, NeedsTesting, Put comment in release notes, priority2

#1120 Add 'raw' format to FormatRenderedProblem.pm
  conf/webwork.apache2.4-config.dist
  lib/FormatRenderedProblem.pm
Labels: Enhancement, PreTeXt, essentially ready to merge, priority 1

#1211 Make the "Render Problem" button on the Set Detail page show the correct problem
  htdocs/js/apps/ProblemSetDetail2/problemsetdetail2.js
  lib/WeBWorK/ContentGenerator/Instructor/ProblemSetDetail2.pm
  lib/WeBWorK/ContentGenerator/instructorXMLHandler.pm
  lib/WebworkWebservice/RenderProblem.pm
Labels: essentially ready to merge

#1121 Fix applets in gateway quizzes
  htdocs/js/apps/AppletSupport/AC_RunActiveContent.js
  htdocs/js/apps/AppletSupport/ww_applet_support.js
  htdocs/js/apps/Problem/problem.js
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
Labels: Enhancement, Put comment in release notes, essentially ready to merge, priority 1 (high)

#1237 Add a couple of missing periods on the show me another page.
  lib/WeBWorK/ContentGenerator/ShowMeAnother.pm
Labels: essentially ready to merge, priority2 (moderate)

#1231 Fix the problem editor 3 take action button
  htdocs/js/apps/PGProblemEditor3/pgproblemeditor3.js
Labels: NeedsTesting, priority 1 (high)

#1218 Remove the onmouseover event from the attempts table answer previews
  htdocs/themes/math3/math3.css
  htdocs/themes/math3/math3.js
  htdocs/themes/math3/system.template
  htdocs/themes/math4/math4.css
  htdocs/themes/math4/math4.js
  lib/WeBWorK/Utils/AttemptsTable.pm
Labels: essentially ready to merge

#1148 Drop user and key from URL when session_cookie session management is in use
  lib/WeBWorK/ContentGenerator.pm
Labels: Enhancement, essentially ready to merge

#1149 Cookie code refactor, Use CGI::Cookie and support samesite
  Dockerfile
  bin/check_modules.pl
  conf/defaults.config
  conf/localOverrides.conf.dist
  lib/WeBWorK/Authen.pm
  lib/WeBWorK/ContentGenerator/Logout.pm
  lib/WeBWorK/Cookie.pm
Labels: Enhancement, NeedsTesting, Put comment in release notes, Requires Attention, essentially ready to merge, priority2 (moderate)

#1199 LTI authentication patches
  lib/WeBWorK/Authen/LTIAdvanced.pm
Labels: Enhancement, essentially ready to merge, priority2 (moderate)

#1200 Update the mathquill javascript.
  htdocs/js/apps/MathQuill/mathquill.js
  htdocs/js/apps/MathQuill/mathquill.min.js
Labels: essentially ready to merge

#1163 Fix the WebworkWebservice permission handling
  conf/webwork.apache2.4-config.dist
  lib/WebworkWebservice.pm
Labels: priority 1 (high)

#1177 LTI grade pass-back - improved code
  conf/authen_LTI.conf.dist
  lib/WeBWorK/Authen/LTIAdvanced/SubmitGrade.pm
Labels: Enhancement, Put comment in release notes, priority2 (moderate)

#1154 UTF-8 changes
  bin/importClassList.pl
  lib/Apache/WeBWorK.pm
  lib/FormatRenderedProblem.pm
  lib/WeBWorK/ContentGenerator.pm
  lib/WeBWorK/ContentGenerator/Feedback.pm
  lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm
  lib/WeBWorK/ContentGenerator/Instructor/SendMail.pm
  lib/WeBWorK/ContentGenerator/Instructor/SetMaker.pm
  lib/WeBWorK/ContentGenerator/Instructor/UserList2.pm
  lib/WeBWorK/ContentGenerator/Login.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
  lib/WeBWorK/ContentGenerator/ProblemUtil/ProblemUtil.pm
  lib/WeBWorK/Request.pm
  lib/WeBWorK/Utils.pm
  lib/WebworkClient.pm
Labels: Multilingual, essentially ready to merge

#1197 Fix to iteration over GWQ problems in case of missing numbers part 2
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Grades.pm
Labels: essentially ready to merge

#1239 Make PGML work for hardcopy if used in a set header file
  Dockerfile
  bin/check_modules.pl
  conf/snippets/ASimpleCombinedHeaderFile.pg
  conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-oneColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-oneColumn/hardcopyProblemDivider.tex
  conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-twoColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/XeLaTeX-Hebrew-twoColumn/hardcopyProblemDivider.tex
  conf/snippets/hardcopyThemes/XeLaTeX-oneColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/XeLaTeX-oneColumn/hardcopyProblemDivider.tex
  conf/snippets/hardcopyThemes/XeLaTeX-oneColumn/hardcopySetFooter.pg
  conf/snippets/hardcopyThemes/XeLaTeX-twoColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/XeLaTeX-twoColumn/hardcopyProblemDivider.tex
  conf/snippets/hardcopyThemes/common/CAPA.tex
  conf/snippets/hardcopyThemes/common/PGML.tex
  conf/snippets/hardcopyThemes/common/packages.tex
  conf/snippets/hardcopyThemes/oneColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/oneColumn/hardcopyProblemDivider.tex
  conf/snippets/hardcopyThemes/twoColumn/hardcopyPreamble.tex
  conf/snippets/hardcopyThemes/twoColumn/hardcopyProblemDivider.tex
  conf/snippets/setHeader.pg
  conf/webwork.apache2.4-config.dist
  courses.dist/modelCourse/templates/ASimpleCombinedHeaderFile.pg
  courses.dist/modelCourse/templates/ASimpleHardCopyHeaderFile.pg
  htdocs/themes/math4/math4.css
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Hardcopy.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
  lib/WeBWorK/ContentGenerator/ShowMeAnother.pm
Labels: Do Not Merge Yet, NeedsTesting, priority 1 (high)

#1258 Add css files requested by problems to gateway quizzes
  lib/WeBWorK/ContentGenerator/GatewayQuiz.pm
  lib/WeBWorK/ContentGenerator/Problem.pm
Labels: Put comment in release notes, essentially ready to merge, priority2 (moderate)

#1280 Make LMS name configurable
  conf/authen_LTI.conf.dist
  lib/WeBWorK/Authen/LTIBasic.pm
  lib/WeBWorK/Authz.pm
  lib/WeBWorK/ContentGenerator/Login.pm
  lib/WeBWorK/ContentGenerator/Logout.pm
  lib/WeBWorK/ContentGenerator/ProblemSets.pm
  lib/WeBWorK/Localize.pm
Labels: Enhancement, priority2 (moderate)

#1287 Install Mathjax via npm
  htdocs/mathjax
  htdocs/package-lock.json
  htdocs/package.json
Labels: Put comment in release notes

#1242 Merge after #1160 - Docker - update to using Ubuntu 20.04 + minor changes related to recent PRs
  Dockerfile
  docker-compose.yml
  docker-config/db/limits.conf
  docker-config/db/mariadb.cnf
  docker-config/db/my.cnf
  docker-config/docker-entrypoint.sh
  docker-config/imagemagick-allow-pdf-read.patch
  docker-config/xmlrpc-lite-utf8-fix.patch
Labels: Do Not Merge Yet, priority 1 (high)

#1282 display problem sets by urgency, with GW versions under their GW temp…
  htdocs/themes/math4/math4.css
  lib/WeBWorK/ContentGenerator/ProblemSets.pm
Labels: Enhancement, priority2 (moderate)

#1214 Update the translation pot and po files to pull in strings that have been added in the code.
  bin/update_localization_files
  lib/WeBWorK/ContentGenerator/Hardcopy.pm
  lib/WeBWorK/ContentGenerator/Instructor/FileManager.pm
  lib/WeBWorK/ContentGenerator/ProblemSets.pm
  lib/WeBWorK/Localize.pm
  lib/WeBWorK/Localize/cs_CZ.po
  lib/WeBWorK/Localize/en.po
  lib/WeBWorK/Localize/en_us.po
  lib/WeBWorK/Localize/es.po
  lib/WeBWorK/Localize/fr.po
  lib/WeBWorK/Localize/heb.po
  lib/WeBWorK/Localize/hu.po
  lib/WeBWorK/Localize/ko.po
  lib/WeBWorK/Localize/ru_RU.po
  lib/WeBWorK/Localize/tr.po
  lib/WeBWorK/Localize/webwork2.pot
  lib/WeBWorK/Localize/zh_CN.po
  lib/WeBWorK/Localize/zh_hk.po
Labels: Multilingual, priority 1 (high)
