Repository openwebwork/webwork2, pull requests merged in 2021-07, with the labels that each got.

#1398 Limit html2xml grade pass-back to when it is explicitly allowed.
  lib/FormatRenderedProblem.pm
Labels: priority 1 (high)

#1298 LTIAdvanced: assign all Achievements to a new user
  lib/WeBWorK/Authen/LTIAdvanced.pm
Labels: priority3 (low)

#1430 Stop making ping calls to webwork.maa.org during Apache startup
  conf/webwork.apache2-config.dist
  conf/webwork.apache2.4-config.dist
Labels: priority3 (low)

#1431 Past answer table: resize fields + limit allowed length of a set name accordingly
  bin/addcourse
  conf/defaults.config
  lib/WeBWorK/ContentGenerator/CourseAdmin.pm
  lib/WeBWorK/ContentGenerator/Instructor/ProblemSetList.pm
  lib/WeBWorK/DB/Record/PastAnswer.pm
  lib/WeBWorK/Utils/CourseManagement.pm
  lib/WebworkWebservice/CourseActions.pm
Labels: NeedsTesting, priority2 (moderate)

#1405 WW 2.16 - mods to admin page for collecting site info / security group signup
  conf/defaults.config
  htdocs/themes/math4/math4.css
  lib/WeBWorK/ContentGenerator/CourseAdmin.pm
Labels: priority2 (moderate)

#1403 LTI (Advanced) modify user_id selection
  conf/authen_LTI.conf.dist
  lib/WeBWorK/Authen/LTIAdvanced.pm
  lib/WeBWorK/Authen/LTIBasic.pm
Labels: Put comment in release notes, priority2 (moderate)

#1438 Docker - use main instead of master branch (only to be merged when 2.16 is about to be merged into main)
  docker-compose.yml
Labels: priority3 (low)
