Repository openwebwork/webwork2, pull requests merged in 2022-02, with the labels that each got.

#1572 Update some dependency data (develop pre-2.17)
  bin/check_modules.pl
Labels: Do Not Merge Yet, priority2 (moderate), Put comment in release notes, maintainer discussion needed

#1577 Codemirror editor improvements.
  htdocs/js/apps/AchievementEditor/achievementeditor.js
  htdocs/js/apps/PGCodeMirror/PGaddons.js
  htdocs/js/apps/PGCodeMirror/codemirror.css
  htdocs/js/apps/PGProblemEditor/pgproblemeditor.js
  htdocs/themes/math4/math4.scss
  lib/WeBWorK/ContentGenerator/Instructor/AchievementEditor.pm
  lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
Labels: documentation needed

#1558 Add the capability for students to add attachments to feedback emails.
  bin/check_modules.pl
  conf/site.conf.dist
  lib/WeBWorK/ContentGenerator.pm
  lib/WeBWorK/ContentGenerator/Feedback.pm
  lib/WeBWorK/ContentGenerator/Instructor/SendMail.pm
  lib/WeBWorK/ContentGenerator/ProblemUtil/ProblemUtil.pm
Labels: Put comment in release notes
