Repository openwebwork/webwork2, pull requests merged in 2022-03, with the labels that each got.

#1546 Fix the WebworkSOAP endpoint - develop.
  conf/webwork.apache2.4-config.dist
  lib/WebworkSOAP.pm
  lib/WebworkSOAP/Classes/GlobalProblem.pm
  lib/WebworkSOAP/Classes/GlobalSet.pm
  lib/WebworkSOAP/Classes/Key.pm
  lib/WebworkSOAP/Classes/Password.pm
  lib/WebworkSOAP/Classes/Permission.pm
  lib/WebworkSOAP/Classes/User.pm
  lib/WebworkSOAP/Classes/UserProblem.pm
  lib/WebworkSOAP/Classes/UserSet.pm
Labels: Put comment in release notes

#1474 Optionally remove student id from feedback
  conf/defaults.config
  conf/localOverrides.conf.dist
  lib/WeBWorK/ContentGenerator/Feedback.pm
  lib/WeBWorK/Localize.pm
  lib/WeBWorK/Localize/cs_CZ.po
  lib/WeBWorK/Localize/en.po
  lib/WeBWorK/Localize/en_us.po
  lib/WeBWorK/Localize/es.po
  lib/WeBWorK/Localize/fr.po
  lib/WeBWorK/Localize/heb.po
  lib/WeBWorK/Localize/hu.po
  lib/WeBWorK/Localize/ko.po
  lib/WeBWorK/Localize/ru_RU.po
  lib/WeBWorK/Localize/tr.po
  lib/WeBWorK/Localize/webwork2.pot
  lib/WeBWorK/Localize/zh_CN.po
  lib/WeBWorK/Localize/zh_hk.po
Labels: NeedsTesting, priority3 (low), Put comment in release notes

#1519 LTI bug fix + reimplement test of when to update the nonce in the DB
  bin/ww_purge_old_nonces
  lib/WeBWorK/Authen/LTIAdvanced.pm
  lib/WeBWorK/Authen/LTIBasic.pm
Labels: priority2 (moderate)

#1608 Improve the PG Problem Editor and Achievement Editor with CodeMirror options
  htdocs/helpFiles/InstructorPGProblemEditor.html
  htdocs/js/apps/AchievementEditor/achievementeditor.js
  htdocs/js/apps/PGCodeMirror/PG.js
  htdocs/js/apps/PGCodeMirror/pgeditor.css
  htdocs/js/apps/PGCodeMirror/pgeditor.js
  htdocs/js/apps/PGProblemEditor/pgproblemeditor.js
  htdocs/themes/math4/math4.scss
  htdocs/third-party-assets.json
  lib/WeBWorK/ContentGenerator/Instructor/AchievementEditor.pm
  lib/WeBWorK/ContentGenerator/Instructor/CodeMirrorEditor.pm
  lib/WeBWorK/ContentGenerator/Instructor/PGProblemEditor.pm
Labels: Put comment in release notes
